// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irjtwahjruziclvmzpfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyanR3YWhqcnV6aWNsdm16cGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NTUwMjksImV4cCI6MjA2NDIzMTAyOX0.JBRRjZbxEja0r-gLqPaO1hTq76SQQNc6wHBuW2A2Kho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);